# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

url                      : "https://whoiswho.fredhutch.org"
baseurl                  : ""
repository               : "FredHutch/who-is-who"
logo                     : "/images/tall-dasl-site.png" 
description              : "Home of the Fred Hutch Data Science Lab"
title                    : ""

minimal_mistakes_skin: contrast
search: false

analytics:
  provider               : "google-gtag" # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          :  "G-6ZC2S7M38Y"
    anonymize_ip         : # true, false (default)



# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.24.0
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: America/Los_Angeles # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages


search                   :  true #, false (default)
search_full_content      :  true #, false (default)

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache


footer:
  links:
    - label: "See our GitHub Org"
      icon: "fab fa-fw fa-github"
      url: https://github.com/fhdsl
    - label: "Join the Conversation on Slack"
      icon: "fab fa-fw fa-slack"
      url: https://fhdata.slack.com/
    - label: "Read Fred Hutch Data Science Docs"
      icon: "fas fa-book"
      url: https://sciwiki.fredhutch.org

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      read_time: false
      comments: false
      share: true
      related: true
      sidebar:
        nav: "frontpage"
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "frontpage"

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
