version: '3.3'
services:
  whoiswho:
    networks:
      - proxy
    image: sc-registry.fredhutch.org/whoiswho:latest
    deploy:
      restart_policy:
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.whoiswho.rule=Host(`whoiswho.fredhutch.org`)"
        - "traefik.http.routers.whoiswho-secured.rule=Host(`whoiswho.fredhutch.org`)"
        - "traefik.http.routers.whoiswho.entrypoints=web,web-secured"
        - "traefik.http.services.whoiswho.loadbalancer.server.port=80" # it seems you always need to give traefik a port so it 'notices' the service
        - "traefik.http.routers.whoiswho.tls=true"

                          
networks:
  proxy:
    external: true